export const rows = [
  {
    id: 'sw-1',
    title: 'The Phantom Menace',
    episode: 1,
    description:
      'Two Jedi Knights escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their old glory.',
    rating: 6.5,
    premiere: new Date(1999, 4, 19),
    hasLeiaInIt: false,
    espectadores: 92430000,
    ingresos: 1027000000,
    review: '',
  },
  {
    id: 'sw-2',
    title: 'Attack of the Clones',
    episode: 2,
    description:
      'Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-Wan Kenobi investigates an assassination attempt on the senator and discovers a secret clone army crafted for the Jedi.',
    rating: 6.5,
    premiere: new Date(2002, 4, 16),
    hasLeiaInIt: false,
    espectadores: 65590000,
    ingresos: 649400000,
    review: '',
  },
  {
    id: 'sw-3',
    title: 'Revenge of the Sith',
    episode: 3,
    description:
      'Three years into the Clone Wars, the Jedi rescue Palpatine from Count Dooku. As Obi-Wan pursues a new threat, Anakin acts as a double agent between the Jedi Council and Palpatine and is lured into a sinister plan to rule the galaxy.',
    rating: 7.5,
    premiere: new Date(2005, 4, 19),
    hasLeiaInIt: false,
    espectadores: 85140000,
    ingresos: 868400000,
    review: '',
  },
  {
    id: 'sw-4',
    title: 'A New Hope',
    episode: 4,
    description:
      "Luke Skywalker begins a journey that will change the galaxy, as he joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to rescue Princess Leia from the Empire's world-destroying battle-station, while also attempting to destroy the evil Empire.",
    rating: 8.6,
    premiere: new Date(1977, 4, 25),
    hasLeiaInIt: true,
    espectadores: 152300000,
    ingresos: 775400000,
    review: '',
  },
  {
    id: 'sw-5',
    title: 'The Empire Strikes Back',
    episode: 5,
    description:
      "Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Jedi Master Yoda. Only with Yoda's help can Luke survive when the Dark Side of the Force beckons him into the ultimate duel with Darth Vader.",
    rating: 8.7,
    premiere: new Date(1980, 4, 21),
    hasLeiaInIt: true,
    espectadores: 121200000,
    ingresos: 547900000,
    review: '',
  },
  {
    id: 'sw-6',
    title: 'Return of the Jedi',
    episode: 6,
    description:
      'Luke Skywalker battles horrible Jabba the Hut and cruel Darth Vader to save his comrades in the Rebel Alliance and triumph over the Galactic Empire. Han Solo and Princess Leia reaffirm their love, and team with Chewbacca, Lando Calrissian, the Ewoks and the androids C-3PO and R2-D2 to aid in the disruption of the Dark Side and the defeat of the evil emperor.',
    rating: 8.3,
    premiere: new Date(1983, 5, 25),
    hasLeiaInIt: true,
    espectadores: 104200000,
    ingresos: 475100000,
    review: '',
  },
  {
    id: 'sw-7',
    title: 'The Force Awakens',
    episode: 7,
    description:
      'As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.',
    rating: 7.9,
    premiere: new Date(2015, 11, 18),
    hasLeiaInIt: true,
    espectadores: 119200000,
    ingresos: 2068000000,
    review: '',
  },
  {
    id: 'sw-8',
    title: 'The Last Jedi',
    episode: 8,
    description:
      'Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares for battle with the First Order.',
    rating: 7.0,
    premiere: new Date(2017, 11, 9),
    hasLeiaInIt: true,
    espectadores: 95150000,
    ingresos: 1333000000,
    review: '',
  },
  {
    id: 'sw-9',
    title: 'The Rise of Skywalker',
    episode: 9,
    description:
      'The surviving Resistance faces the First Order once more in the final chapter of the Skywalker saga.',
    rating: 6.6,
    premiere: new Date(2019, 11, 16),
    hasLeiaInIt: true,
    espectadores: 92600000,
    ingresos: 1074000000,
    review: '',
  },
]

export const rowsChildren = [
  ...rows,
  {
    title: 'Off timeline',
    episode: 'n',
    description: 'Some side timelines',
    rating: 7.8,
    premiere: new Date(2016, 11, 10),
    hasLeiaInIt: true,
    espectadores: 69040000 + 21450000,
    ingresos: 1056000000 + 393200000,
    review: '',
    children: [
      {
        title: 'Rogue One',
        episode: 'Rogue One',
        description:
          'The daughter of an Imperial scientist joins the Rebel Alliance in a risky move to steal the Death Star plans.',
        rating: 7.8,
        premiere: new Date(2016, 11, 10),
        hasLeiaInIt: true,
        espectadores: 69040000,
        ingresos: 1056000000,
        review: '',
      },
      {
        title: 'Solo',
        episode: 'Solo',
        description:
          'During an adventure into the criminal underworld, Han Solo meets his future co-pilot Chewbacca and encounters Lando Calrissian years before joining the Rebellion.',
        rating: 6.9,
        premiere: new Date(2018, 4, 10),
        hasLeiaInIt: false,
        espectadores: 21450000,
        ingresos: 393200000,
        review: '',
      },
    ],
  },
]
